export type Question = {
  id: number;
  domain: string;
  objective: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
};

const q = (domain:string, objective:string, prompt:string, options:string[], answer:number, explanation:string): Omit<Question,'id'> => ({domain,objective,prompt,options,answer,explanation});

const items: Omit<Question,'id'>[] = [
  q('Identity & governance','Users and groups','You need a group whose membership updates automatically from each user’s department property. Which group type should you use?',['Assigned security group','Dynamic user security group','Microsoft 365 assigned group','Administrative unit'],1,'A dynamic user group evaluates a membership rule against user properties such as department.'),
  q('Identity & governance','User properties and licensing','Before assigning a Microsoft cloud-service licence to a new user, which user property must normally be set?',['Usage location','Job title','Employee ID','Office location'],0,'Microsoft Entra uses Usage location to determine which licensed services are available in a country or region.'),
  q('Identity & governance','Group licensing','You assign a product licence to a Microsoft Entra group. What happens to a new user added to that group?',['Nothing until an admin assigns it directly','The licence is inherited through group-based licensing','The user becomes a group owner','A temporary licence is issued for 30 days'],1,'Group-based licensing automatically assigns configured licences to eligible members.'),
  q('Identity & governance','External users','A supplier must access an Azure-hosted application using the supplier’s existing identity. What should you create?',['A managed identity','A B2B guest user','A service principal','A cloud-only Global Administrator'],1,'Microsoft Entra External ID B2B collaboration lets guests use their existing external identity.'),
  q('Identity & governance','SSPR','You want only members of a pilot group to reset their own passwords. Which SSPR setting should you configure?',['Registration campaign','Enabled: Selected','Password writeback only','Authentication methods: One'],1,'The Selected scope enables self-service password reset for a chosen group.'),
  q('Identity & governance','Azure roles','A user must manage virtual machines but must not assign Azure roles. Which built-in role is the best fit?',['Owner','Contributor','Virtual Machine Contributor','User Access Administrator'],2,'Virtual Machine Contributor manages VMs without granting role-assignment permissions.'),
  q('Identity & governance','Role scope','A role assigned at resource-group scope applies to which resources?',['Only current resources','Current and future resources in that group','All resources in the subscription','Only resources with matching tags'],1,'Azure RBAC assignments inherit down the scope hierarchy, including to future resources.'),
  q('Identity & governance','Access assignments','A user has Reader at subscription scope and Contributor at one resource group. What can the user do in that resource group?',['Read only','Manage resources but not grant access','Grant access only','Nothing because Reader overrides Contributor'],1,'Azure RBAC permissions are additive; Contributor applies in the resource group but cannot assign roles.'),
  q('Identity & governance','Azure Policy','Which Azure Policy effect blocks creation of a noncompliant resource?',['Audit','Append','Deny','DeployIfNotExists'],2,'The Deny effect prevents a request that does not satisfy the policy rule.'),
  q('Identity & governance','Resource locks','Which lock prevents deletion while allowing authorised configuration changes?',['ReadOnly','CanNotDelete','DenyAssignment','Immutable'],1,'CanNotDelete permits updates but blocks deletion; ReadOnly blocks updates too.'),
  q('Identity & governance','Tags','A resource group has a CostCenter tag. Do resources inside automatically inherit that tag?',['Yes, always','Only resources created later','No, not without a policy or automation','Only resources in the same region'],2,'Tags do not inherit automatically. Azure Policy can append or inherit tags.'),
  q('Identity & governance','Resource groups','Which statement about Azure resource groups is correct?',['Every resource must belong to one resource group','A resource can belong to several resource groups','All resources must share the group’s region','Deleting a group keeps its resources'],0,'Every Azure resource belongs to exactly one resource group; its region can differ from the group metadata location.'),
  q('Identity & governance','Cost management','Which feature notifies you when forecast or actual Azure spending reaches a threshold?',['Service Health','Cost Management budget','Resource Health','Defender secure score'],1,'Budgets can evaluate actual or forecast costs and trigger notifications.'),
  q('Identity & governance','Management groups','A governance assignment must cover several subscriptions. What is the highest useful scope?',['Resource','Resource group','Management group','Availability zone'],2,'Management groups organize subscriptions and allow inherited governance across them.'),

  q('Storage','Storage networking','A storage account should accept public-endpoint traffic only from a selected VNet subnet. What should you configure?',['Storage firewall plus a service endpoint','A public IP prefix','An NSG on the storage account','A route table on the account'],0,'Selected networks uses the storage firewall; a Microsoft.Storage service endpoint identifies the allowed subnet.'),
  q('Storage','SAS tokens','A client needs blob upload access for two hours without an account key. What should you issue?',['A shared access signature','A resource lock','A private DNS zone','A copy of the access key'],0,'A SAS grants scoped permissions for a defined resource and time window.'),
  q('Storage','Stored access policies','Why use a stored access policy with a service SAS?',['It increases storage capacity','It allows server-side revocation or expiry changes','It enables zone redundancy','It replaces encryption'],1,'Changing or deleting the stored access policy can revoke associated service SAS tokens.'),
  q('Storage','Access keys','What is the safest rotation pattern for storage account access keys?',['Regenerate both at once','Move clients to key 2, regenerate key 1, then repeat','Disable HTTPS first','Copy the primary key to Key Vault and never rotate it'],1,'Two keys allow clients to move to one while the other is regenerated, avoiding downtime.'),
  q('Storage','Identity access for Azure Files','Which approach avoids distributing storage keys when users access Azure Files?',['Anonymous access','Identity-based SMB authentication and Azure RBAC','A container-level SAS','Blob index tags'],1,'Azure Files supports identity-based authentication combined with share-level Azure RBAC permissions.'),
  q('Storage','Storage accounts','Which account type is recommended for most blob, file, queue, and table workloads?',['General-purpose v2','Premium block blob only','Classic storage','FileStorage for every workload'],0,'General-purpose v2 supports the broadest set of current Azure Storage features.'),
  q('Storage','Redundancy','Which option synchronously replicates data across availability zones in one region?',['LRS','ZRS','GRS','RA-GRS'],1,'Zone-redundant storage copies data synchronously across zones in the primary region.'),
  q('Storage','Object replication','Which feature must be enabled on both source and destination accounts for blob object replication?',['Static website','Blob versioning','SFTP','Infrastructure encryption'],1,'Object replication relies on blob versioning, and change feed is required on the source.'),
  q('Storage','Encryption','Where should you keep a customer-managed key used by Azure Storage encryption?',['Azure Key Vault or Managed HSM','A public blob container','A VM temporary disk','An NSG rule'],0,'Azure Storage customer-managed keys are protected in Key Vault or Managed HSM.'),
  q('Storage','Storage tools','Which command-line tool is optimized for high-performance copying to and from Azure Storage?',['AzCopy','Azure Policy','Network Watcher','Bicep'],0,'AzCopy is the specialized high-throughput transfer utility for blobs and files.'),
  q('Storage','Azure Files','What provides a point-in-time, read-only copy of an Azure file share?',['Share snapshot','Blob version','Object replication policy','Stored access policy'],0,'A share snapshot captures the state of an Azure file share at a point in time.'),
  q('Storage','Blob tiers','Which access tier has the lowest storage cost but requires rehydration before data can be read?',['Hot','Cool','Cold','Archive'],3,'Archive is offline and must be rehydrated to an online tier before access.'),
  q('Storage','Soft delete','What should you enable to recover a blob deleted accidentally during the retention window?',['Blob soft delete','Object replication','Static website','Hierarchical namespace'],0,'Blob soft delete retains deleted blobs for a configured number of days.'),
  q('Storage','Lifecycle management','Old blobs should move to the cool tier automatically after 30 days. What should you configure?',['Object replication','Lifecycle management rule','Stored access policy','Azure File Sync'],1,'Lifecycle rules transition or delete blobs based on age and conditions.'),
  q('Storage','Blob versioning','What does blob versioning create when an existing block blob is modified?',['A new storage account','A previous version that can be restored','A file-share snapshot','A second access key'],1,'Versioning automatically preserves earlier versions when a blob is written or deleted.'),

  q('Compute','ARM and Bicep','In Bicep, which construct supplies a value at deployment time?',['param','output','resourceId','existing'],0,'A param declaration exposes an input that can be supplied during deployment.'),
  q('Compute','ARM and Bicep','You need to deploy the same infrastructure repeatedly and consistently. What should you use?',['An ARM template or Bicep file','A Resource Health alert','A manual portal checklist','A DNS zone export'],0,'ARM and Bicep provide declarative, repeatable Azure resource deployments.'),
  q('Compute','ARM and Bicep','Which Azure CLI command converts an ARM JSON template to Bicep?',['az bicep decompile','az deployment validate','az vm convert','az resource export'],0,'az bicep decompile converts ARM template JSON into a Bicep starting point.'),
  q('Compute','ARM and Bicep','What can the Azure portal Export template feature produce from a resource group?',['An ARM template representing supported resources','A complete backup','A billing invoice','A KQL workbook'],0,'Export template generates an ARM representation, although exported templates often need review before reuse.'),
  q('Compute','Virtual machines','Which VM setting chiefly determines vCPU count and memory?',['VM size','Resource group','Computer name','Availability set'],0,'The selected VM size defines compute, memory, and related limits.'),
  q('Compute','VM encryption','Which feature encrypts data at the Azure compute host before it reaches the storage service?',['Encryption at host','ReadOnly lock','Accelerated networking','Boot diagnostics'],0,'Encryption at host encrypts temporary disks and disk-cache data on the host.'),
  q('Compute','Move resources','Can an Azure VM be moved directly to another region using the resource-group Move command?',['Yes, always','No; use a regional move/replication approach','Only if it has a public IP','Only when stopped'],1,'Cross-region VM moves require a supported regional move method such as Azure Resource Mover, not a normal scope move.'),
  q('Compute','Managed disks','You need a point-in-time copy of a managed disk that can create another disk. What should you create?',['Snapshot','Availability set','Image definition only','Proximity placement group'],0,'A managed disk snapshot is a read-only point-in-time copy that can create disks.'),
  q('Compute','Availability','Which option protects VMs from a full datacenter failure within a region?',['Availability zones','Resource groups','Management groups','Proximity placement groups'],0,'Availability zones are physically separate datacenter groupings within a region.'),
  q('Compute','Availability','Availability sets distribute VMs across which two logical groupings?',['Fault domains and update domains','Regions and geographies','Tenants and subscriptions','VNets and subnets'],0,'Fault domains reduce shared hardware risk; update domains reduce simultaneous planned maintenance.'),
  q('Compute','VM Scale Sets','Identical web VMs must scale automatically with demand. Which service fits?',['Availability set','Virtual Machine Scale Sets','Dedicated Host','Azure Batch account'],1,'VM Scale Sets manage and autoscale groups of similarly configured VMs.'),
  q('Compute','Container Registry','What is Azure Container Registry primarily used for?',['Storing and managing private container images','Running virtual machines','Resolving private DNS','Collecting platform metrics'],0,'ACR is a managed registry for container images and related artifacts.'),
  q('Compute','Container Instances','A container must run quickly without an orchestrator or VM management. Which service is simplest?',['AKS','Azure Container Instances','VM Scale Sets','App Service Environment'],1,'ACI runs containers directly without managing servers or a cluster.'),
  q('Compute','Container Apps','Which service runs microservices with revision management and event-driven scaling without managing Kubernetes?',['Azure Container Apps','Azure Container Registry','Azure Batch','Dedicated Host'],0,'Container Apps provides managed revisions, ingress, and KEDA-based scaling.'),
  q('Compute','Container scaling','Which Container Apps setting can reduce an inactive app to zero replicas?',['A scale rule with minimum replicas set to 0','An availability set','A ReadOnly lock','A deployment slot'],0,'Supported event-driven scale rules can scale Container Apps to zero when min replicas is zero.'),
  q('Compute','App Service plans','What does an App Service plan define?',['Region, operating system, pricing tier, and compute capacity','Only the app name','The DNS zone registrar','The Entra tenant'],0,'The plan supplies the compute resources and feature tier used by its apps.'),
  q('Compute','App Service scaling','Which action adds more App Service instances?',['Scale up','Scale out','Slot swap','TLS binding'],1,'Scale out changes instance count; scale up changes the plan tier or instance size.'),
  q('Compute','App Service TLS','What must be added to App Service before binding HTTPS to a custom hostname?',['A certificate covering the hostname','A route table','A Recovery Services vault','A managed disk'],0,'The app needs an appropriate private certificate, managed certificate, or imported certificate for the binding.'),
  q('Compute','App Service custom domains','Which DNS record commonly maps a subdomain such as www to the default App Service hostname?',['CNAME','MX','PTR','SRV'],0,'A CNAME maps a subdomain to the app’s default azurewebsites.net hostname.'),
  q('Compute','App Service backup','What does App Service backup require as its destination?',['An Azure Storage account container','A Log Analytics workspace','A private DNS zone','An NSG'],0,'App Service backups are stored in an Azure Storage container.'),
  q('Compute','App Service networking','Which feature lets an App Service app make outbound calls into a virtual network?',['VNet integration','A deployment slot','A custom domain','An availability set'],0,'Regional VNet integration enables outbound access from the app into a VNet.'),
  q('Compute','Deployment slots','Which App Service feature lets you validate a release before swapping it into production?',['Deployment slot','Availability zone','Application group','Update domain'],0,'Deployment slots provide live staging environments and controlled swaps.'),
  q('Compute','Deployment slots','Which setting should remain with a deployment slot rather than move during a swap?',['A setting marked as a deployment slot setting','The default hostname','The resource group name','The App Service plan region'],0,'Sticky deployment slot settings remain with their original slot during swaps.'),

  q('Networking','VNets and subnets','Can two peered VNets have overlapping address spaces?',['Yes','No','Only with Standard public IPs','Only in the same subscription'],1,'VNet peering requires non-overlapping IP address spaces.'),
  q('Networking','VNet peering','VNet A peers with B, and B peers with C. Does A automatically communicate with C through peering?',['Yes, peering is transitive','No, peering is non-transitive','Only when B has a load balancer','Only across regions'],1,'VNet peering is not transitive; another connection or routing design is required.'),
  q('Networking','Public IP addresses','Which allocation method is used for Standard SKU public IP addresses?',['Static','Dynamic only','Round robin','Ephemeral'],0,'Standard public IPs use static allocation.'),
  q('Networking','User-defined routes','Which route can override an applicable Azure system route for subnet traffic?',['User-defined route','NSG rule','DNS record','Service tag'],0,'A UDR controls the next hop and can override applicable system routes.'),
  q('Networking','Connectivity troubleshooting','Which Network Watcher tool checks whether an NSG permits a specific packet flow?',['IP flow verify','Cost Analysis','Activity Log','Azure Advisor'],0,'IP flow verify evaluates the effective NSG rules for a specified flow.'),
  q('Networking','NSGs and ASGs','What is the purpose of an application security group?',['Group VM network interfaces for use in NSG rules','Create DNS records','Store application secrets','Replicate VNets'],0,'ASGs let NSG rules refer to logical application groups rather than explicit IP addresses.'),
  q('Networking','NSG priority','Which NSG rule is evaluated first?',['Priority 4096','Priority 100','The newest rule','The longest name'],1,'NSG rules are processed in ascending priority order; lower numbers run first.'),
  q('Networking','Effective security rules','Where can you see the combined NSG rules applied to a VM network interface?',['Effective security rules','Cost Management','Resource Graph only','Service Health'],0,'Effective security rules combine rules from the subnet and network interface scopes.'),
  q('Networking','Azure Bastion','Administrators need browser-based RDP/SSH to VMs without public IPs. Which service fits?',['Azure Bastion','Traffic Manager','Front Door','NAT Gateway'],0,'Azure Bastion provides RDP/SSH over TLS without public IPs on target VMs.'),
  q('Networking','Service endpoints','What remains the destination address when a subnet uses a service endpoint to reach Azure Storage?',['The service’s public endpoint','A private endpoint NIC','The subnet gateway','A Bastion host'],0,'Service endpoints secure the route and identify the subnet, but the service still uses its public endpoint.'),
  q('Networking','Private endpoints','A storage account must be reached through a private IP in your VNet. What should you create?',['Service tag','Private endpoint','Public IP prefix','Application security group'],1,'A private endpoint places a private IP-backed network interface for the service in the VNet.'),
  q('Networking','Private DNS','What commonly makes an Azure PaaS hostname resolve to its private endpoint IP inside a VNet?',['A linked private DNS zone','A public load balancer','A route table only','An ASG'],0,'The appropriate privatelink private DNS zone, linked to the VNet, resolves the service name privately.'),
  q('Networking','Azure DNS','To host a child DNS domain in a separate Azure DNS zone, what must you add to the parent zone?',['NS delegation records','An NSG','A private endpoint','An MX-only record'],0,'NS records in the parent delegate the child domain to the child zone’s name servers.'),
  q('Networking','Load Balancer','What does an Azure Load Balancer health probe determine?',['Which backend instances can receive new flows','Which users have RBAC access','The monthly cost','DNS record ownership'],0,'The health probe removes unhealthy backend instances from new traffic distribution.'),
  q('Networking','Load balancing troubleshooting','A load-balancing rule exists, but every backend probe fails. What happens to new connections?',['They are not sent to the unhealthy backends','They are sent round robin anyway','They bypass the load balancer','They are converted to HTTP'],0,'When all probe targets are unhealthy, the load balancer does not distribute new flows to them.'),

  q('Monitoring & recovery','Azure Monitor metrics','Which Azure Monitor data type is best for near-real-time numerical time-series values?',['Metrics','Activity log only','Resource locks','Tags'],0,'Metrics are lightweight numerical time-series data suited to fast alerting and charts.'),
  q('Monitoring & recovery','Diagnostic settings','What routes platform logs and metrics from a resource to Log Analytics or a storage account?',['Diagnostic setting','Resource lock','Deployment slot','Availability set'],0,'Diagnostic settings choose categories and destinations for resource logs and metrics.'),
  q('Monitoring & recovery','Log queries','Which language queries a Log Analytics workspace?',['KQL','Bicep','T-SQL only','XPath'],0,'Kusto Query Language is used to query and analyze Azure Monitor Logs.'),
  q('Monitoring & recovery','Alerts','What defines who is notified or which automation runs when an Azure Monitor alert fires?',['Action group','Data collection rule','Workbook','Metric namespace'],0,'Action groups contain notification receivers and automated actions.'),
  q('Monitoring & recovery','Alert processing','You need to suppress notifications during planned maintenance without disabling alert rules. What should you use?',['Alert processing rule','Resource lock','Budget','Service endpoint'],0,'Alert processing rules can suppress or redirect actions during a schedule.'),
  q('Monitoring & recovery','Monitor Insights','Which experience provides curated monitoring views for VMs, storage accounts, and networks?',['Azure Monitor Insights','Cost exports','Azure Policy initiatives','Management groups'],0,'Azure Monitor Insights provides workload-specific monitoring visualizations and configuration.'),
  q('Monitoring & recovery','Network Watcher','Which tool continuously tests and reports connectivity between endpoints?',['Connection Monitor','Advisor','Deployment Center','Cost Analysis'],0,'Network Watcher Connection Monitor provides ongoing end-to-end connection monitoring.'),
  q('Monitoring & recovery','Backup vaults','Which vault commonly protects Azure VMs with Azure Backup?',['Key vault','Recovery Services vault','Storage account','Container registry'],1,'A Recovery Services vault stores Azure VM backup data and policies.'),
  q('Monitoring & recovery','Backup policies','What does an Azure Backup policy define?',['Backup schedule and retention','NSG priority','VM size','DNS TTL only'],0,'Backup policies specify when recovery points are created and how long they are retained.'),
  q('Monitoring & recovery','Backup restore','Which Azure VM restore option creates disks from a recovery point for custom recovery steps?',['Restore disks','Replace all resource groups','Reapply NSG','Swap deployment slot'],0,'Restore disks produces managed disks and a template so you can control VM reconstruction.'),
  q('Monitoring & recovery','Site Recovery','Which service provides orchestrated regional disaster recovery for Azure VMs?',['Azure Site Recovery','Azure Update Manager','Azure Advisor','Application Insights'],0,'Site Recovery replicates workloads and orchestrates failover and failback.'),
  q('Monitoring & recovery','Failover','What should you run to validate a Site Recovery plan without affecting production replication?',['Test failover','Unplanned failover','Commit','Delete recovery points'],0,'A test failover validates recovery in an isolated network without interrupting ongoing replication.'),
  q('Monitoring & recovery','Backup reporting','What centralizes Azure Backup job, policy, and usage reporting across vaults?',['Backup reports using Azure Monitor Logs','Public IP diagnostics','App Service deployment logs','DNS analytics only'],0,'Backup reports use diagnostic data in Log Analytics for cross-vault reporting and analysis.')
];

export const questions: Question[] = items.map((item,index)=>({...item,id:index+1}));
export const domains = ['All domains','Identity & governance','Storage','Compute','Networking','Monitoring & recovery'];
